---

checkmk_server_version: "2.4.0"
checkmk_server_edition: "cre"
checkmk_server_sites:
  - name: "master"
    version: "{{ checkmk_server_version }}"
    update_conflict_resolution: "abort"
    state: started
    admin_pw: "{{ checkmk_admin_pw }}"
checkmk_admin_pw: "AnsibleW0rkshop2025!"
checkmk_folders:
  - path: /linux
    attributes:
      labels:
        os: almalinux
      tag_agent: "cmk-agent"
  - path: /linux/checkmk
checkmk_users:
  - name: cmkuser
    password: "AnsibleW0rkshop2025!"
    email: "cmkuser@localhost"
    fullname: "Checkmk user"
    auth_type: password
    contactgroups:
      - "all"
    roles:
      - "user"
checkmk_rules:
  - ruleset: "checkgroup_parameters:agent_update"
    rule:
      properties:
        description: "Checkmk Agent version"
      location:
        folder: "/linux"
      value_raw: "{'agent_version': ('site', {}), 'agent_version_missmatch': 1, 'legacy_pull_mode': 2}"
  - ruleset: "active_checks:httpv2"
    rule:
      properties:
        description: "authenticationtest.com"
      location:
        folder: "/"
      value_raw: "{'endpoints': [{'service_name': {'prefix': 'auto', 'name': 'HTTPAuth'}, 'url': 'https://authenticationtest.com/HTTPAuth/'}], 'standard_settings': {'connection': {'method': ('get', None), 'auth': ('user_auth', {'user': 'user', 'password': ('cmk_postprocessed', 'stored_password', ('authenticationtest_com', ''))})}}}"
      conditions:
        host_name:
          match_on:
            - cmk-agent
          operator: one_of
checkmk_passwords:
  - name: authenticationtest_com
    title: authenticationtest.com
    password: pass
checkmk_tag_groups:
  - name: lifecycle_environment
    title: Lifecycle Environment
    tags:
      - id: production
        title: Production
      - id: testing
        title: Testing
