---

checkmk_server_version: "2.4.0"
checkmk_server_edition: "cre"
checkmk_server_sites:
  - name: "master"
    version: "{{ checkmk_server_version }}"
    update_conflict_resolution: "abort"
    state: started
    admin_pw: "{{ checkmk_admin_pw }}"
checkmk_admin_pw: "AnsibleW0rkshop2025!"
checkmk_folders:
  - path: /linux
    attributes:
      labels:
        os: almalinux
      tag_agent: "cmk-agent"
  - path: /linux/checkmk
