---

- name: Install Checkmk agent
  hosts: cmk-agent
  connection: local
  become: true

  pre_tasks:
    - name: Install required Python packages
      ansible.builtin.dnf:
        name: python3-netaddr
        state: installed

  roles:
    - checkmk.general.agent
